# model.py
import requests

def analyze_diff(diff_text: str) -> str:
    prompt = f"""
You are an AI DevOps assistant.
Analyze the following code diff and provide a detailed response with:

1. **Summary of the intent of the change**  
2. **Recommended deployment strategy**  
3. **Infrastructure components impacted**  
4. **Tests to run before deploying**  
5. **Additional notes or risks**

Diff:
{diff_text}
"""

    try:
        response = requests.post(
            "http://localhost:11434/api/generate",
            json={"model": "gemma:2b", "prompt": prompt},
            timeout=120
        )
        response.raise_for_status()
        data = response.json()
        return data.get("response", "⚠️ No analysis generated by Ollama.")
    except Exception as e:
        return f"❌ Error calling Ollama: {str(e)}"

